language: android
branches:
  except:
      - /^v.*/
android:
  components:
    # The BuildTools version used by your project
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-22
before_script:
  - yes | sdkmanager 'platforms;android-28'
  - export MEDIC_VERSION_NAME="1.4.5.$(expr 1097 + $TRAVIS_BUILD_NUMBER)"
  - echo "Building medic-collect-${MEDIC_VERSION_NAME}"
script:
  - ./gradlew --stacktrace test assembleDebug
after_success:
  - git config --global user.email "dev@medicmobile.org"
  - git config --global user.name "Travis CI"
  - git tag "v${MEDIC_VERSION_NAME}"
  - git push --tags "https://${github_auth}@github.com/${TRAVIS_REPO_SLUG}" >/dev/null 2>/dev/null
before_deploy:
  # For historical reasons, Android versionCode started at 1097, and versionName
  # starts with `1.4.5.`
  - export MEDIC_PUBLISH_DIR="build/publish/${MEDIC_VERSION_NAME}"
  - mkdir -p "$MEDIC_PUBLISH_DIR"
  - cp build/outputs/apk/*-debug.apk "$MEDIC_PUBLISH_DIR"
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: ${s3_access_id}
  secret_access_key:
    secure: ${s3_access_secret}
  bucket: medic-mobile
  local_dir: build/publish
  upload-dir: builds/medic-collect
  acl: public_read
  on:
    repo: ${TRAVIS_REPO_SLUG}
    branch: master
